# Generated by Django 2.2.7 on 2020-04-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprints.Blueprint')),
            ],
        ),
    ]
